name: smarting_ui_component_library
description: "This is the ui component library for all the Flutters projects by Smarting"
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: lib/fonts/titillium_web/TitilliumWeb-Black.ttf
          weight: 900

        - asset: lib/fonts/titillium_web/TitilliumWeb-Bold.ttf
          weight: 700

        - asset: lib/fonts/titillium_web/TitilliumWeb-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: lib/fonts/titillium_web/TitilliumWeb-ExtraLight.ttf
          weight: 200

        - asset: lib/fonts/titillium_web/TitilliumWeb-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: lib/fonts/titillium_web/TitilliumWeb-Italic.ttf
          weight: 400
          style: italic

        - asset: lib/fonts/titillium_web/TitilliumWeb-Light.ttf
          weight: 300

        - asset: lib/fonts/titillium_web/TitilliumWeb-LightItalic.ttf
          weight: 300
          style: italic

        - asset: lib/fonts/titillium_web/TitilliumWeb-Regular.ttf
          weight: 400

        - asset: lib/fonts/titillium_web/TitilliumWeb-SemiBold.ttf
          weight: 600

        - asset: lib/fonts/titillium_web/TitilliumWeb-SemiBoldItalic.ttf
          weight: 600
          style: italic





